### ISSUE TITLE
Getting wrong return values from read-object function

### ISSUE THREAD

**Issue by FerdiKuehne** [pkpkpk/fress#5]
Good Day Sir,
#### Description
I'm currently working on a cljs k-v store. For the de- and serializer i use your library. After i update ``CIDER 0.17.0`` to ``CIDER 0.21.0`` the deserializer is not working anymore.

Somehow the read-object function holds old values.
     
#### Screenshots
![screenshot at 2019-01-22 16 58 28](https://user-images.githubusercontent.com/16018948/51547757-328bd380-1e67-11e9-9819-bab1bb34646e.png)

On the top left you can see the deserializer. I added println function to highlight the read problem (line 35 and 40).
Bottom left is a simple example code for the filestore and on the right you can see the execution. 
As u can see the read-object function return 47 and i never saved that value in the store.

##### env
Leiningen:  ``2.8.3`` on Java 1.8.0_201 Java HotSpot(TM) 64-Bit Server VM
Leiningen profiles.clj:  ``{:user {:plugins [[cider/cider-nrepl "0.20.0"]]}}``
Node: ``v10.12.0``
##### test
git clone https://git@github.com:FerdiKuehne/incognito.git
lein install
git clone https://github.com/FerdiKuehne/konserve.git
lein cljsbuild test

the serializer is located at konserve/src/konserve/serializers.cljc (line 31 - 62)

Thank you very much for your effort in advance. 

Best regards Ferdi

**Comment by pkpkpk** [comment]
It would be helpful if you reduced this down to example input it chokes on or a handler configuration that misbehaves, without extraneous library code. Also, are you on the lastest clojars release or on master

**Comment by FerdiKuehne** [comment]
Okay i will do that. I am sorry for the confusion.

Best regards Ferdi

**Comment by FerdiKuehne** [comment]
I updated my clojure and clojurescript version and now its working. I am really sorry for this mess. I think this issue can be closed.

Best regards Ferdi

**Comment by pkpkpk** [comment]
ok thanks
